In [39]:
import pandas as pd
import numpy as np

# Question 1 - Pandas Version

In [3]:
pd.__version__

'2.0.3'

# Question 2 - How many columns are in the dataset?
As you can see below, 20640 rows.

In [6]:
df = pd.read_csv('housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

# Question 3: Select columns with missing data
'total_bedrooms' has 207 missing rows.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4: Number of unique values in the 'ocean_proximity' column

In [12]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [13]:
len(df['ocean_proximity'].unique())

5

In [14]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

# Question 5: Average value of the 'median_house_value' for the houses near the bay
The filter created to filter 'NEAR BAY' Ocean Proximity. And we find the average median_house_value which is **259212.31179039303**.

In [17]:
filter_1 = df['ocean_proximity']=='NEAR BAY'

In [18]:
df[filter_1].describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [19]:
df[filter_1]['median_house_value'].mean()

259212.31179039303

# Question 6: Has the mean value changed after filling missing values? 

    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?
    
- Filling missing values with mean of the values didn't changed the data as expected.


In [21]:
mean_of_bedrooms =  df['total_bedrooms'].mean()
mean_of_bedrooms

537.8705525375618

In [27]:
df_new = df.copy()
df_new.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [28]:

df_new['total_bedrooms'] = df['total_bedrooms'].fillna(value=mean_of_bedrooms)


In [29]:
df_new.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [30]:
df_new['total_bedrooms'].mean()

537.8705525375617

# Question 7

    1. Select all the options located on islands.
    2. Select only columns housing_median_age, total_rooms, total_bedrooms.
    3. Get the underlying NumPy array. Let's call it X.
    4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    5. Compute the inverse of XTX.
    6. Create an array y with values [950, 1300, 800, 1000, 1300].
    7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    8. What's the value of the last element of w?


In [32]:
filter_1 = df_new['ocean_proximity']=='ISLAND'
df_new[filter_1][["housing_median_age", "total_rooms", "total_bedrooms"]]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [34]:
X = df_new[filter_1][["housing_median_age", "total_rooms", "total_bedrooms"]].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [46]:
# from the https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/01-intro/08-linear-algebra.md

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result


def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [79]:
# XTX = matrix_matrix_multiplication(X.T, X)
XTX = (X.T).dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [80]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [81]:
y = [950, 1300, 800, 1000, 1300]

In [83]:
w = XTXinv.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [84]:
w[-1]

5.6992294550655656